apiVersion: v1
kind: Service
metadata:
  name: netflix-clone
spec:
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      nodePort: 30948
      port: 80
      targetPort: 80
  type: LoadBalancer